<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-Q72SAP8P" failures="0" tests="5" name="com.testng.retry.SamplClassTwo" time="0.021" errors="1" timestamp="2024-02-03T18:01:06 IST" skipped="3">
  <testcase classname="com.testng.retry.SamplClassTwo" name="sampleTestTwoMethodTwo" time="0.003">
    <skipped/>
  </testcase> <!-- sampleTestTwoMethodTwo -->
  <system-out/>
  <testcase classname="com.testng.retry.SamplClassTwo" name="sampleTestTwoMethodTwo" time="0.003">
    <skipped/>
  </testcase> <!-- sampleTestTwoMethodTwo -->
  <system-out/>
  <testcase classname="com.testng.retry.SamplClassTwo" name="sampleTestTwoMethodTwo" time="0.001">
    <error message="/ by zero" type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.testng.retry.SamplClassTwo.sampleTestTwoMethodTwo(SamplClassTwo.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sampleTestTwoMethodTwo -->
  <system-out/>
  <testcase classname="com.testng.retry.SamplClassTwo" name="sampleTestTwoMethodOne" time="0.012"/>
  <system-out/>
  <testcase classname="com.testng.retry.SamplClassTwo" name="sampleTestTwoMethodTwo" time="0.002">
    <skipped/>
  </testcase> <!-- sampleTestTwoMethodTwo -->
  <system-out/>
</testsuite> <!-- com.testng.retry.SamplClassTwo -->
